version: 1.0.{build}

clone_depth: 50

install:
- ps: >-
    {
    Function Execute-Command ($commandPath)
    {
        & $commandPath $args 2>&1
        if ( $LastExitCode -ne 0 ) {
            $host.SetShouldExit( $LastExitCode )
        }
    }
    Function Execute-Bash ()
    {
        Execute-Command 'c:\msys64\usr\bin\bash' '-e' '-c' $args
    }
    Execute-Command "C:\msys64\usr\bin\pacman" -Ss gcc
    Execute-Command "C:\msys64\usr\bin\pacman" -Ss clang
    }

build_script:
- ps: >-
    Execute-Bash true

test_script:
- ps: >-
    Execute-Bash true
