version: 1.0.{build}

clone_depth: 50

install:
- ps: >-
    Function Execute-Command ($commandPath)
    {
        & $commandPath $args 2>&1
        if ( $LastExitCode -ne 0 ) {
            $host.SetShouldExit( $LastExitCode )
        }
    }
    Execute-Command "C:\msys64\usr\bin\pacman" -Ss gcc
