version: 1.0.{build}

clone_depth: 50

environment:
  matrix:
  - target: i686-w64-mingw32
    compiler_path: mingw32
    openssl_path: /c/OpenSSL-Win32
    hardening:
  - target: x86_64-w64-mingw32
    compiler_path: mingw64
    openssl_path: /c/OpenSSL-Win64
    hardening: --disable-gcc-hardening

install:
- ps: Function Execute-Command ($commandPath)
      {
          & $commandPath $args 2>&1
          if ( $LastExitCode -ne 0 ) {
              $host.SetShouldExit( $LastExitCode )
          }
      }
- ps: Function Execute-Bash ()
      {
          Execute-Command 'c:\msys64\usr\bin\bash' '-e' '-c' $args
      }
- ps: Execute-Command "C:\msys64\usr\bin\pacman" -Sy --needed --noconfirm openssl-devel openssl libevent-devel libevent mingw-w64-i686-libevent mingw-w64-x86_64-libevent mingw-w64-i686-openssl mingw-w64-x86_64-openssl mingw-w64-i686-zstd mingw-w64-x86_64-zstd

build_script:
- ps: $oldpath = ${env:Path} -split ';'
- ps: $buildpath = @("C:\msys64\${env:compiler_path}\bin", "C:\msys64\usr\bin") + $oldpath
- ps: $env:Path = @($buildpath) -join ';'
- ps: $env:build = @("${env:APPVEYOR_BUILD_FOLDER}", $env:target) -join '\'
- ps: Set-Location "${env:APPVEYOR_BUILD_FOLDER}"
- ps: Execute-Bash 'autoreconf -i'
- ps: mkdir "${env:build}"
- ps: Set-Location "${env:build}"
- ps: Execute-Bash "which ${env:target}-gcc"
- ps: Execute-Bash "${env:target}-gcc --version"
- ps: Execute-Bash "../configure --prefix=/${env:compiler_path} --build=${env:target} --host=${env:target} --disable-asciidoc --enable-fatal-warnings --with-openssl-dir=${env:openssl_path} ${env:hardening}"
- ps: Execute-Bash "V=1 make -j2"
- ps: Execute-Bash "V=1 make -j2 install"

test_script:
- ps: $oldpath = ${env:Path} -split ';'
- ps: $buildpath = @("C:\msys64\${env:compiler_path}\bin") + $oldpath
- ps: $env:Path = $buildpath -join ';'
- ps: Set-Location "${env:build}"
- ps: Execute-Bash "VERBOSE=1 make -j2 check"

on_failure:
- ps: $oldpath = ${env:Path} -split ';'
- ps: $buildpath = @("C:\msys64\usr\bin") + $oldpath
- ps: $env:Path = @($buildpath) -join ';'
- ps: Set-Location "${env:build}"
- ps: Execute-Bash "7z a logs.zip config.log || true"
- ps: Execute-Bash "7z a logs.zip test-suite.log || true"
- ps: Execute-Bash "appveyor PushArtifact logs.zip || true"
- ps: Execute-Bash "tail -1000 config.log || true"
- ps: Execute-Bash "cat test-suite.log || true"
- cmd: C:\Python27\python.exe %APPVEYOR_BUILD_FOLDER%\scripts\test\appveyor-irc-notify.py irc.oftc.net:6697 tor-ci failure
