language: c

os:
  - linux

sudo:
  - required

dist:
  - trusty

before_install:
  - sudo apt-cache policy gcc || true
  - sudo apt-cache policy gcc-7 || true
  - sudo apt-cache policy gcc-8 || true
  - sudo apt-cache policy clang || true
  - sudo apt-cache policy clang-5.0 || true
  - sudo apt-cache policy clang-6.0 || true
  - sudo apt-cache policy clang-7.0 || true

install:
  - true

script:
  - true
